#!/usr/bin/env ruby

# Run unit tests

live = ARGV.delete('--live')

unless live
  $LOAD_PATH.unshift(File.expand_path('lib'))
end

def run_tests
  if find = ARGV[0]
    unless File.file?(find)
      find = File.join(find, '**', 'test_*.rb')
    end
  else
    find = 'test/suite.rb'
  end

  Dir.glob(find).each do |file|
    next if File.directory?(file)
    load file
  end
end

if $0 == __FILE__
  run_tests
end

